# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: Default
  # name: Default
  # demands: WINDOWS-SERVER-
  # demands: gcplinux
  # vmImage: gcp-windows
  
# strategy:
  # matrix:
  #   Python27:
  #     python.version: '2.7'
    # Python35:
    #   python.version: '3.5'
    # Python36:
    #   python.version: '3.6'
    # Python37:
    #   python.version: '3.7'

# steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '$(python.version)'
#   displayName: 'Use Python $(python.version)'

# - script: |
  #   pip install python
  #   python -m pip install --upgrade pip
  #   pip install -r requirements.txt
  # displayName: 'Install dependencies'
# steps:
#   - script: touch test.txt > "Hello world"

#     displayName: Writing
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      sudo echo 'Hello world'
      sudo touch azurepipeline.txt > "Pipeline working"
      sudo pwd
